services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - auth_service
      - frontend
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway  # Путь к папке с API Gateway
      dockerfile: Dockerfile  # Можно опустить, если файл называется просто Dockerfile
    container_name: api-gateway
    networks:
      - backend
    ports:
      - "1020:8000"
    volumes:
      - ./api-gateway:/var/www  
      # - /var/www/vendor
 #   depends_on:
 #     - auth-service
 #    - request-service
 #     - other_api_service

  auth_service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "1025:8000"
    networks:
      - backend
    volumes:
      - ./auth-service:/var/www
      # - /var/www/vendor
    environment:
      - DB_HOST=db_auth_service
      - DB_PORT=3306
  frontend: 
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - backend
    environment:
      - NODE_ENV=development

  db_auth_service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvp-cloud
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
