services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "1024:80"
    depends_on:
      - api-gateway
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway  # Путь к папке с API Gateway
      dockerfile: Dockerfile  # Можно опустить, если файл называется просто Dockerfile
    container_name: api-gateway
    networks:
      - backend
    ports:
      - "1020:8000"
 #   depends_on:
 #     - auth-service
 #    - request-service
 #     - other_api_service

  auth_service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "1025:8000"
    networks:
      - backend
    volumes:
      - ./auth-service:/var/www
    environment:
      - DB_HOST=db_auth_service
      - DB_PORT=3306

  db_auth_service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvp-cloud
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db-data:

networks:
  backend:
    driver: bridge
